// 棚割管理システム - 型定義
// Data types for the Planogram Management System

// ========================================
// 定数・マスタデータ
// ========================================

export const REGIONS = [
  '北海道',
  '東北',
  '関東',
  '中部',
  '近畿',
  '中国・四国',
  '九州',
  '全地域'
] as const;

export type Region = typeof REGIONS[number];

export const FMTS = ['MEGA', 'SuC', 'SMART', 'GO'] as const;
export type FMT = typeof FMTS[number];

// 単位変換定数
export const SHAKU_TO_CM = 30; // 1尺 = 30cm

// ========================================
// 商品データ (Products)
// ========================================

export interface Product {
  id: string;
  jan: string;
  name: string;
  width: number;   // cm
  height: number;  // cm
  depth: number;   // cm
  category: string;
  imageUrl: string;
  salesRank: number; // 1-100, 1が最高
}

// ========================================
// 店舗データ (Stores)
// ========================================

export interface Store {
  id: string;
  code: string;
  name: string;
  fmt: FMT;
  region: Region;
}

// ========================================
// 棚什器データ (Fixtures)
// ========================================

export interface Fixture {
  id: string;
  name: string;
  width: number;       // cm
  height: number;      // cm
  shelfCount: number;  // 段数
  manufacturer?: string;
  modelNumber?: string;
  installDate?: string;   // ISO date string
  warrantyEndDate?: string; // ISO date string
}

// ========================================
// 店舗棚尺配置データ (Store Fixture Placement)
// ========================================

export interface StoreFixturePlacement {
  id: string;
  storeId: string;
  fixtureId: string;
  positionX: number;  // レイアウト上の位置
  positionY: number;
  order: number;      // 配置順序
}

// ========================================
// 棚ブロック（Building Blocks）
// ========================================

export interface ProductPlacement {
  id: string;
  productId: string;
  shelfIndex: number;  // 何段目か（0-indexed）
  positionX: number;   // 段内の位置（cm）
  faceCount: number;   // フェイス数
}

export interface ShelfBlock {
  id: string;
  name: string;
  description?: string;
  width: number;       // cm（ブロック幅）
  height: number;      // cm（ブロック高さ）
  shelfCount: number;  // 段数
  productPlacements: ProductPlacement[];
  createdAt: string;
  updatedAt: string;
}

// ========================================
// FMT標準棚割 (Standard Planogram)
// ========================================

export interface StandardPlanogramBlock {
  id: string;
  blockId: string;     // ShelfBlock ID
  positionX: number;   // 配置位置
  positionY: number;
}

export interface StandardPlanogramProduct {
  id: string;
  productId: string;
  shelfIndex: number;
  positionX: number;
  faceCount: number;
}

export interface StandardPlanogram {
  id: string;
  fmt: FMT;
  name: string;
  baseStoreId: string;  // 基準となった店舗ID
  width: number;        // 総幅
  height: number;       // 総高さ
  shelfCount: number;
  blocks: StandardPlanogramBlock[];      // 配置されたブロック
  products: StandardPlanogramProduct[];  // 展開された商品（ブロック内商品含む）
  createdAt: string;
  updatedAt: string;
}

// ========================================
// 個店棚割 (Store Planogram)
// ========================================

export type PlanogramStatus = 'pending' | 'generated' | 'warning' | 'error' | 'synced';

export interface StorePlanogramProduct {
  id: string;
  productId: string;
  shelfIndex: number;
  positionX: number;
  faceCount: number;
  isAutoGenerated: boolean;  // 自動生成された商品か
  isCut: boolean;            // カットされた商品か（ルールA適用）
}

export interface StorePlanogram {
  id: string;
  storeId: string;
  standardPlanogramId: string;  // 親となる標準棚割ID
  width: number;
  height: number;
  shelfCount: number;
  products: StorePlanogramProduct[];
  status: PlanogramStatus;
  warnings: string[];          // 警告メッセージ
  createdAt: string;
  updatedAt: string;
  syncedAt?: string;           // 最終同期日時
}

// ========================================
// UI用ヘルパー型
// ========================================

export interface GenerationResult {
  storeId: string;
  storeName: string;
  status: PlanogramStatus;
  message: string;
}
