// 棚割自動生成ルール A/B/C の受け入れテスト（純粋関数テスト）
import { describe, it, expect } from 'vitest';
import type {
    Product,
    StandardPlanogramProduct,
    StorePlanogramProduct,
} from '../data/types';

// ── automationService の applyRuleA / applyRuleB は非公開関数なので、
//    ロジックを再現した純粋関数でテストする ──

// ================================================================
// テストヘルパー
// ================================================================

function makeProduct(id: string, name: string, width: number, salesRank: number): Product {
    return {
        id,
        name,
        jan: `49000000${id}`,
        width,
        height: 200,
        depth: 100,
        salesRank,
        createdAt: '',
        updatedAt: '',
    } as Product;
}

function makeStdProduct(
    id: string,
    productId: string,
    shelfIndex: number,
    positionX: number,
    faceCount: number,
    placedBlockId?: string
): StandardPlanogramProduct {
    return { id, productId, shelfIndex, positionX, faceCount, placedBlockId };
}

// ================================================================
// ルールA: カット処理 (店舗の棚 < 標準)
// ================================================================

function applyRuleA(
    products: StandardPlanogramProduct[],
    productMaster: Product[],
    targetWidth: number
): { products: StorePlanogramProduct[]; warnings: string[] } {
    const warnings: string[] = [];

    const sortedProducts = [...products].sort((a, b) => {
        const prodA = productMaster.find(p => p.id === a.productId);
        const prodB = productMaster.find(p => p.id === b.productId);
        return (prodB?.salesRank || 100) - (prodA?.salesRank || 100);
    });

    const result: StorePlanogramProduct[] = [];
    const shelfIndices = [...new Set(sortedProducts.map(p => p.shelfIndex))];

    for (const shelfIndex of shelfIndices) {
        let shelfProducts = sortedProducts.filter(p => p.shelfIndex === shelfIndex);
        let currentWidth = 0;

        for (const sp of shelfProducts) {
            const product = productMaster.find(p => p.id === sp.productId);
            if (!product) continue;
            currentWidth += product.width * sp.faceCount;
        }

        while (currentWidth > targetWidth && shelfProducts.length > 0) {
            const worstProduct = shelfProducts[0];
            const product = productMaster.find(p => p.id === worstProduct.productId);

            if (!product) {
                shelfProducts = shelfProducts.slice(1);
                continue;
            }

            if (worstProduct.faceCount > 1) {
                worstProduct.faceCount -= 1;
                currentWidth -= product.width;
                warnings.push(`${product.name}: フェイス数を削減 (${worstProduct.faceCount + 1} → ${worstProduct.faceCount})`);
            } else {
                shelfProducts = shelfProducts.slice(1);
                currentWidth -= product.width;
                warnings.push(`${product.name}: カット（売上ランク ${product.salesRank}）`);
            }
        }

        let posX = 0;
        for (const sp of shelfProducts) {
            const product = productMaster.find(p => p.id === sp.productId);
            if (!product) continue;

            result.push({
                id: `gen-${sp.id}`,
                productId: sp.productId,
                shelfIndex: sp.shelfIndex,
                positionX: posX,
                faceCount: sp.faceCount,
                isAutoGenerated: true,
                isCut: false,
            });
            posX += product.width * sp.faceCount;
        }
    }

    return { products: result, warnings };
}

// ================================================================
// ルールB: 拡張処理 (店舗の棚 > 標準)
// ================================================================

function applyRuleB(
    products: StandardPlanogramProduct[],
    productMaster: Product[],
    targetWidth: number,
    _standardWidth: number
): { products: StorePlanogramProduct[]; warnings: string[] } {
    const warnings: string[] = [];

    const rankedProducts = products
        .map(p => ({
            ...p,
            salesRank: productMaster.find(pm => pm.id === p.productId)?.salesRank || 100,
        }))
        .sort((a, b) => a.salesRank - b.salesRank)
        .slice(0, 10);

    const top10Ids = new Set(rankedProducts.map(p => p.productId));

    const shelfIndices = [...new Set(products.map(p => p.shelfIndex))];
    const result: StorePlanogramProduct[] = [];

    for (const shelfIndex of shelfIndices) {
        const shelfProducts = products
            .filter(p => p.shelfIndex === shelfIndex)
            .map(p => ({ ...p }));

        let currentUsed = 0;
        for (const sp of shelfProducts) {
            const product = productMaster.find(p => p.id === sp.productId);
            if (product) currentUsed += product.width * sp.faceCount;
        }

        // 1st pass: 2倍
        for (const sp of shelfProducts) {
            if (!top10Ids.has(sp.productId)) continue;
            const product = productMaster.find(p => p.id === sp.productId);
            if (!product) continue;

            const extraNeeded = product.width * sp.faceCount;
            const available = targetWidth - currentUsed;

            if (available >= extraNeeded) {
                const oldFace = sp.faceCount;
                sp.faceCount = oldFace * 2;
                currentUsed += product.width * oldFace;
                warnings.push(`${product.name}: フェイス2倍 (${oldFace} → ${sp.faceCount})`);
            }
        }

        // 2nd pass: 1.5倍
        for (const sp of shelfProducts) {
            if (!top10Ids.has(sp.productId)) continue;
            const product = productMaster.find(p => p.id === sp.productId);
            if (!product) continue;

            const originalSp = products.find(p => p.productId === sp.productId && p.shelfIndex === sp.shelfIndex);
            if (!originalSp || sp.faceCount !== originalSp.faceCount) continue;

            const newFaceCount = Math.floor(sp.faceCount * 1.5);
            if (newFaceCount <= sp.faceCount) continue;

            const extraNeeded = product.width * (newFaceCount - sp.faceCount);
            const available = targetWidth - currentUsed;

            if (available >= extraNeeded) {
                const oldFace = sp.faceCount;
                sp.faceCount = newFaceCount;
                currentUsed += product.width * (newFaceCount - oldFace);
                warnings.push(`${product.name}: フェイス1.5倍 (${oldFace} → ${sp.faceCount})`);
            }
        }

        let posX = 0;
        for (const sp of shelfProducts) {
            const product = productMaster.find(p => p.id === sp.productId);
            if (!product) continue;

            result.push({
                id: `gen-${sp.id}`,
                productId: sp.productId,
                shelfIndex: sp.shelfIndex,
                positionX: posX,
                faceCount: sp.faceCount,
                isAutoGenerated: true,
                isCut: false,
            });
            posX += product.width * sp.faceCount;
        }

        if (targetWidth - currentUsed > 10) {
            warnings.push(`段${shelfIndex + 1}: ${Math.round(targetWidth - currentUsed)}mmの余白あり`);
        }
    }

    return { products: result, warnings };
}

// ================================================================
// 直接コピー (同幅)
// ================================================================

function applyDirectCopy(
    products: StandardPlanogramProduct[]
): { products: StorePlanogramProduct[]; warnings: string[] } {
    return {
        products: products.map(p => ({
            id: `gen-${p.id}`,
            productId: p.productId,
            shelfIndex: p.shelfIndex,
            positionX: p.positionX,
            faceCount: p.faceCount,
            isAutoGenerated: true,
            isCut: false,
        })),
        warnings: [],
    };
}

// ================================================================
// テスト本体
// ================================================================

describe('ルールA: カット処理', () => {
    // 基本商品マスタ: 幅100mm、ランク1(最良)~5(最悪)
    const products: Product[] = [
        makeProduct('p1', '商品A', 100, 1),
        makeProduct('p2', '商品B', 100, 2),
        makeProduct('p3', '商品C', 100, 3),
        makeProduct('p4', '商品D', 100, 4),
        makeProduct('p5', '商品E', 100, 5),
    ];

    it('幅がちょうど収まる場合はカットなし', () => {
        const stdProducts = [
            makeStdProduct('s1', 'p1', 0, 0, 1),
            makeStdProduct('s2', 'p2', 0, 100, 1),
            makeStdProduct('s3', 'p3', 0, 200, 1),
        ];
        const result = applyRuleA(stdProducts, products, 300);
        expect(result.products).toHaveLength(3);
        expect(result.warnings).toHaveLength(0);
    });

    it('幅オーバー時にランク最低商品のフェイスを先に削減', () => {
        // 商品A(1)x2, 商品B(2)x2, 商品E(5)x2 → 幅600mm、ターゲット500mm
        const stdProducts = [
            makeStdProduct('s1', 'p1', 0, 0, 2),
            makeStdProduct('s2', 'p2', 0, 200, 2),
            makeStdProduct('s3', 'p5', 0, 400, 2), // ランク5（最悪）
        ];
        const result = applyRuleA(stdProducts, products, 500);

        // 商品E(ランク5)のフェイスが2→1に削減
        const productE = result.products.find(p => p.productId === 'p5');
        expect(productE?.faceCount).toBe(1);
        expect(result.warnings.some(w => w.includes('商品E') && w.includes('削減'))).toBe(true);
    });

    it('フェイス1からさらに削減 → 商品カット', () => {
        // 全て1フェイス、幅500mm中300mmに収める必要あり
        const stdProducts = [
            makeStdProduct('s1', 'p1', 0, 0, 1),   // ランク1
            makeStdProduct('s2', 'p2', 0, 100, 1),  // ランク2
            makeStdProduct('s3', 'p3', 0, 200, 1),  // ランク3
            makeStdProduct('s4', 'p4', 0, 300, 1),  // ランク4
            makeStdProduct('s5', 'p5', 0, 400, 1),  // ランク5
        ];
        const result = applyRuleA(stdProducts, products, 300);

        // 3商品残り、ランク4,5がカット
        expect(result.products).toHaveLength(3);
        const remainIds = result.products.map(p => p.productId);
        expect(remainIds).toContain('p1');
        expect(remainIds).toContain('p2');
        expect(remainIds).toContain('p3');
        expect(remainIds).not.toContain('p4');
        expect(remainIds).not.toContain('p5');
    });

    it('カット後のpositionXが再計算される', () => {
        const stdProducts = [
            makeStdProduct('s1', 'p1', 0, 0, 2),    // 200mm, ランク1
            makeStdProduct('s2', 'p5', 0, 200, 2),   // 200mm, ランク5(最悪)
            makeStdProduct('s3', 'p2', 0, 400, 1),   // 100mm, ランク2
        ];
        const result = applyRuleA(stdProducts, products, 300);

        // ソートは売上ランク降順なので: p5(5), p2(2), p1(1) の順で処理
        // p5のフェイス2→1(100mm削減)→合計400mm、まだ>300
        // p5のフェイス1→カット(100mm削減)→合計300mm
        // 残り: p1(200mm)+p2(100mm)=300mm
        // ただしpositionXはsorted順（ランク降順）で再計算される
        // p2(ランク2) → posX=0, p1(ランク1) → posX=100
        const p1 = result.products.find(p => p.productId === 'p1');
        const p2 = result.products.find(p => p.productId === 'p2');
        expect(p2?.positionX).toBe(0);
        expect(p1?.positionX).toBe(100);
    });

    it('複数段に対して独立にカット処理が行われる', () => {
        const stdProducts = [
            // 段0: 幅300mm
            makeStdProduct('s1', 'p1', 0, 0, 1),
            makeStdProduct('s2', 'p2', 0, 100, 1),
            makeStdProduct('s3', 'p5', 0, 200, 1),
            // 段1: 幅300mm
            makeStdProduct('s4', 'p3', 1, 0, 1),
            makeStdProduct('s5', 'p4', 1, 100, 1),
            makeStdProduct('s6', 'p5', 1, 200, 1), // p5が段1にも
        ];
        const result = applyRuleA(stdProducts, products, 200);

        // 各段で独立にカット
        const shelf0 = result.products.filter(p => p.shelfIndex === 0);
        const shelf1 = result.products.filter(p => p.shelfIndex === 1);
        expect(shelf0).toHaveLength(2);
        expect(shelf1).toHaveLength(2);
    });

    it('全商品isAutoGenerated=trueかつisCut=false', () => {
        const stdProducts = [
            makeStdProduct('s1', 'p1', 0, 0, 1),
            makeStdProduct('s2', 'p5', 0, 100, 2),
        ];
        const result = applyRuleA(stdProducts, products, 200);
        for (const p of result.products) {
            expect(p.isAutoGenerated).toBe(true);
            expect(p.isCut).toBe(false);
        }
    });

    it('ターゲット幅が非常に小さい場合、全商品がカットされうる', () => {
        const stdProducts = [
            makeStdProduct('s1', 'p1', 0, 0, 1), // 100mm
            makeStdProduct('s2', 'p2', 0, 100, 1),
        ];
        const result = applyRuleA(stdProducts, products, 50);
        // 50mm以下に収めるため全カット
        expect(result.products).toHaveLength(0);
        expect(result.warnings.length).toBeGreaterThanOrEqual(2);
    });
});

describe('ルールB: 拡張処理', () => {
    // 12商品：ランク1~12
    const products: Product[] = Array.from({ length: 12 }, (_, i) =>
        makeProduct(`p${i + 1}`, `商品${String.fromCharCode(65 + i)}`, 100, i + 1)
    );

    it('トップ10商品のフェイスが2倍に拡張される', () => {
        // 12商品中、ランク1~10がtop10、ランク11,12がtop10外
        // ただしtop10は「stdProducts内のランク上位10」で選ばれる
        // 3商品しかないので全てtop10になる → p11もtop10
        // top10外テストは別テストで行う
        const stdProducts = [
            makeStdProduct('s1', 'p1', 0, 0, 1),   // ランク1
            makeStdProduct('s2', 'p2', 0, 100, 1),  // ランク2
            makeStdProduct('s3', 'p11', 0, 200, 1), // ランク11（3商品中最低だがtop10内）
        ];
        const result = applyRuleB(stdProducts, products, 600, 300);

        const p1 = result.products.find(p => p.productId === 'p1');
        const p2 = result.products.find(p => p.productId === 'p2');
        const p11 = result.products.find(p => p.productId === 'p11');
        expect(p1?.faceCount).toBe(2);
        expect(p2?.faceCount).toBe(2);
        expect(p11?.faceCount).toBe(2); // 3商品なので全てtop10
    });

    it('2倍に拡張するスペースがない場合1.5倍を試みる', () => {
        // 1段に3商品、各1フェイス（幅100mm）= 300mm標準
        // ターゲット400mm → 2倍にするには200mm追加が必要だが100mmしかない
        const stdProducts = [
            makeStdProduct('s1', 'p1', 0, 0, 1),
            makeStdProduct('s2', 'p2', 0, 100, 1),
            makeStdProduct('s3', 'p3', 0, 200, 1),
        ];
        // ターゲット350mm: 2倍(200mm追加)は不可、1.5倍(50mm追加)は可能
        // ただしfaceCount 1 → floor(1.5)=1 なので変わらない
        // faceCount=2の場合テスト
        const stdProducts2 = [
            makeStdProduct('s1', 'p1', 0, 0, 2),   // 200mm
            makeStdProduct('s2', 'p2', 0, 200, 2),  // 200mm
        ];
        // ターゲット600mm: 標準400mm → 200mm余裕
        // p1: 2倍→4face→追加200mm → ぴったり使い切り
        const result = applyRuleB(stdProducts2, products, 600, 400);
        const p1 = result.products.find(p => p.productId === 'p1');
        expect(p1?.faceCount).toBe(4); // 2→4
    });

    it('Top10外の商品は拡張されない', () => {
        // 11商品以上をstdProductsに入れ、ランク11以降をtop10外にする
        const stdProducts: StandardPlanogramProduct[] = [];
        for (let i = 1; i <= 12; i++) {
            stdProducts.push(makeStdProduct(`s${i}`, `p${i}`, 0, (i - 1) * 100, 1));
        }
        // top10はp1~p10、p11,p12はtop10外
        const result = applyRuleB(stdProducts, products, 3000, 1200);

        const p11 = result.products.find(p => p.productId === 'p11');
        const p12 = result.products.find(p => p.productId === 'p12');
        expect(p11?.faceCount).toBe(1); // top10外
        expect(p12?.faceCount).toBe(1); // top10外
    });

    it('余白がある場合に警告が生成される', () => {
        const stdProducts = [
            makeStdProduct('s1', 'p11', 0, 0, 1), // top10外、拡張されない
        ];
        const result = applyRuleB(stdProducts, products, 500, 100);

        // 余白400mm → 警告あり
        expect(result.warnings.some(w => w.includes('余白'))).toBe(true);
    });

    it('拡張後のpositionXが正しく再計算される', () => {
        const stdProducts = [
            makeStdProduct('s1', 'p1', 0, 0, 1),   // 100mm → 200mm(2倍)
            makeStdProduct('s2', 'p11', 0, 100, 1), // 100mm(変わらず)
        ];
        const result = applyRuleB(stdProducts, products, 500, 200);

        const p1 = result.products.find(p => p.productId === 'p1');
        const p11 = result.products.find(p => p.productId === 'p11');
        expect(p1?.positionX).toBe(0);
        expect(p11?.positionX).toBe(200); // p1が200mmに拡張された分ずれる
    });

    it('複数段で各段独立に拡張処理', () => {
        const stdProducts = [
            makeStdProduct('s1', 'p1', 0, 0, 1),
            makeStdProduct('s2', 'p2', 1, 0, 1),
        ];
        const result = applyRuleB(stdProducts, products, 300, 100);

        const shelf0 = result.products.filter(p => p.shelfIndex === 0);
        const shelf1 = result.products.filter(p => p.shelfIndex === 1);

        // 各段で独立にp1,p2が2倍
        expect(shelf0[0]?.faceCount).toBe(2);
        expect(shelf1[0]?.faceCount).toBe(2);
    });

    it('全商品isAutoGenerated=true', () => {
        const stdProducts = [
            makeStdProduct('s1', 'p1', 0, 0, 1),
        ];
        const result = applyRuleB(stdProducts, products, 300, 100);
        for (const p of result.products) {
            expect(p.isAutoGenerated).toBe(true);
        }
    });
});

describe('直接コピー (同幅)', () => {
    it('全商品が1:1でコピーされる', () => {
        const stdProducts = [
            makeStdProduct('s1', 'p1', 0, 0, 3),
            makeStdProduct('s2', 'p2', 0, 300, 2),
            makeStdProduct('s3', 'p3', 1, 0, 1),
        ];
        const result = applyDirectCopy(stdProducts);

        expect(result.products).toHaveLength(3);
        expect(result.warnings).toHaveLength(0);

        for (let i = 0; i < stdProducts.length; i++) {
            expect(result.products[i].productId).toBe(stdProducts[i].productId);
            expect(result.products[i].faceCount).toBe(stdProducts[i].faceCount);
            expect(result.products[i].positionX).toBe(stdProducts[i].positionX);
            expect(result.products[i].shelfIndex).toBe(stdProducts[i].shelfIndex);
            expect(result.products[i].isAutoGenerated).toBe(true);
            expect(result.products[i].isCut).toBe(false);
        }
    });

    it('空の標準棚割からは空の個店棚割が生成される', () => {
        const result = applyDirectCopy([]);
        expect(result.products).toHaveLength(0);
        expect(result.warnings).toHaveLength(0);
    });
});

describe('ルール判定ロジック（幅比較）', () => {
    function determineRule(storeWidth: number, standardWidth: number): 'A' | 'B' | 'copy' {
        if (storeWidth < standardWidth) return 'A';
        if (storeWidth > standardWidth) return 'B';
        return 'copy';
    }

    it('店舗幅 < 標準幅 → ルールA', () => {
        expect(determineRule(6000, 9000)).toBe('A');
    });

    it('店舗幅 > 標準幅 → ルールB', () => {
        expect(determineRule(12000, 9000)).toBe('B');
    });

    it('店舗幅 = 標準幅 → 直接コピー', () => {
        expect(determineRule(9000, 9000)).toBe('copy');
    });

    it('店舗幅 = 0 → ルールA（什器なし）', () => {
        // 実際のサービスでは warning を返すが、純粋な比較ではルールA
        expect(determineRule(0, 9000)).toBe('A');
    });
});

describe('ルールA: エッジケース', () => {
    const products = [
        makeProduct('p1', '商品A', 150, 1),
        makeProduct('p2', '商品B', 80, 5),
    ];

    it('商品幅が異なる場合も正しくカット', () => {
        const stdProducts = [
            makeStdProduct('s1', 'p1', 0, 0, 2),   // 300mm
            makeStdProduct('s2', 'p2', 0, 300, 2),  // 160mm → 合計460mm
        ];
        // ターゲット350mm: p2(ランク5)のフェイス削減→カット
        const result = applyRuleA(stdProducts, products, 350);

        const p1 = result.products.find(p => p.productId === 'p1');
        const p2 = result.products.find(p => p.productId === 'p2');
        expect(p1?.faceCount).toBe(2); // ランク1はそのまま
        // p2はフェイス削減またはカットされて350mm以下に収まる
        const totalWidth = result.products.reduce((sum, sp) => {
            const prod = products.find(p => p.id === sp.productId)!;
            return sum + prod.width * sp.faceCount;
        }, 0);
        expect(totalWidth).toBeLessThanOrEqual(350);
    });

    it('同じランクの商品が複数ある場合もフェイス削減が行われる', () => {
        const sameRankProducts = [
            makeProduct('pa', '商品X', 100, 3),
            makeProduct('pb', '商品Y', 100, 3),
        ];
        const stdProducts = [
            makeStdProduct('s1', 'pa', 0, 0, 2),
            makeStdProduct('s2', 'pb', 0, 200, 2),
        ];
        const result = applyRuleA(stdProducts, sameRankProducts, 300);

        const totalWidth = result.products.reduce((sum, sp) => {
            const prod = sameRankProducts.find(p => p.id === sp.productId)!;
            return sum + prod.width * sp.faceCount;
        }, 0);
        expect(totalWidth).toBeLessThanOrEqual(300);
    });
});

describe('ルールB: エッジケース', () => {
    const products = Array.from({ length: 15 }, (_, i) =>
        makeProduct(`p${i + 1}`, `商品${i + 1}`, 100, i + 1)
    );

    it('10商品以下の場合は全てがtop10対象', () => {
        const stdProducts = [
            makeStdProduct('s1', 'p1', 0, 0, 1),
            makeStdProduct('s2', 'p2', 0, 100, 1),
        ];
        const result = applyRuleB(stdProducts, products, 600, 200);

        // 両方top10なので拡張される
        expect(result.products.every(p => p.faceCount >= 2)).toBe(true);
    });

    it('faceCount=1の場合 floor(1*1.5)=1 なので1.5倍は効果なし', () => {
        const stdProducts = [
            makeStdProduct('s1', 'p1', 0, 0, 1),
        ];
        // 2倍にするスペースがちょうどない場合
        // 100mm → 2倍で200mmだが、ターゲット150mm（50mm余裕）
        // 1.5倍: floor(1*1.5)=1 → 変わらず
        const result = applyRuleB(stdProducts, products, 150, 100);

        // 2倍には50mm不足 → フォールバック1.5倍 → floor(1*1.5)=1 → 変更なし
        const p1 = result.products.find(p => p.productId === 'p1');
        expect(p1?.faceCount).toBe(1);
    });

    it('十分なスペースがあれば複数商品が2倍になる', () => {
        const stdProducts = [
            makeStdProduct('s1', 'p1', 0, 0, 1),
            makeStdProduct('s2', 'p2', 0, 100, 1),
            makeStdProduct('s3', 'p3', 0, 200, 1),
        ];
        // 標準300mm → ターゲット900mm（3倍のスペース）
        const result = applyRuleB(stdProducts, products, 900, 300);

        // 全てtop10で十分なスペースがあるので全て2倍
        for (const p of result.products) {
            expect(p.faceCount).toBe(2);
        }
    });
});

describe('統合パターン: 大中小店舗', () => {
    // ダミーデータと同じ構成のテスト
    const products = [
        makeProduct('beef1', '国産牛テール', 130, 1),
        makeProduct('beef2', '国産牛切り落とし', 120, 2),
        makeProduct('beef3', '国産牛こま切れ', 110, 3),
        makeProduct('pork1', '国産豚バラ薄切り', 120, 11),
        makeProduct('pork2', '国産豚こま切れ', 110, 12),
        makeProduct('chicken1', '鶏もも肉', 130, 21),
    ];

    // 標準棚割: 2段、幅3600mm（12尺）
    const standardProducts: StandardPlanogramProduct[] = [
        // 段0
        makeStdProduct('s1', 'beef1', 0, 0, 3),       // 390mm
        makeStdProduct('s2', 'beef2', 0, 390, 3),      // 360mm
        makeStdProduct('s3', 'beef3', 0, 750, 3),      // 330mm
        makeStdProduct('s4', 'pork1', 0, 1080, 3),     // 360mm
        makeStdProduct('s5', 'pork2', 0, 1440, 3),     // 330mm
        makeStdProduct('s6', 'chicken1', 0, 1770, 3),  // 390mm → 合計2160mm
        // 段1
        makeStdProduct('s7', 'beef1', 1, 0, 3),
        makeStdProduct('s8', 'beef2', 1, 390, 3),
        makeStdProduct('s9', 'beef3', 1, 750, 3),
        makeStdProduct('s10', 'pork1', 1, 1080, 3),
        makeStdProduct('s11', 'pork2', 1, 1440, 3),
        makeStdProduct('s12', 'chicken1', 1, 1770, 3),
    ];
    const standardWidth = 2160;

    it('大型店舗(店舗幅 > 標準): ルールBで拡張', () => {
        const storeWidth = 3600; // > 2160
        const result = applyRuleB(standardProducts, products, storeWidth, standardWidth);

        // 商品数は減らない
        expect(result.products.length).toBeGreaterThanOrEqual(standardProducts.length);

        // top10商品のフェイスが拡張されている
        const beef1s = result.products.filter(p => p.productId === 'beef1');
        expect(beef1s.some(p => p.faceCount > 3)).toBe(true);

        // 各段の幅がstoreWidth以下
        const shelf0 = result.products.filter(p => p.shelfIndex === 0);
        const shelf0Width = shelf0.reduce((sum, sp) => {
            const prod = products.find(p => p.id === sp.productId)!;
            return sum + prod.width * sp.faceCount;
        }, 0);
        expect(shelf0Width).toBeLessThanOrEqual(storeWidth);
    });

    it('小型店舗(店舗幅 < 標準): ルールAでカット', () => {
        const storeWidth = 1500; // < 2160
        const result = applyRuleA(standardProducts, products, storeWidth);

        // 商品数は減る
        expect(result.products.length).toBeLessThanOrEqual(standardProducts.length);

        // 各段の幅がstoreWidth以下
        for (const shelfIdx of [0, 1]) {
            const shelfProducts = result.products.filter(p => p.shelfIndex === shelfIdx);
            const shelfWidth = shelfProducts.reduce((sum, sp) => {
                const prod = products.find(p => p.id === sp.productId)!;
                return sum + prod.width * sp.faceCount;
            }, 0);
            expect(shelfWidth).toBeLessThanOrEqual(storeWidth);
        }

        // ランク最良の商品(beef1, ランク1)は残っている
        expect(result.products.some(p => p.productId === 'beef1')).toBe(true);
    });

    it('同型店舗(店舗幅 = 標準): 直接コピー', () => {
        const result = applyDirectCopy(standardProducts);
        expect(result.products).toHaveLength(standardProducts.length);
        expect(result.warnings).toHaveLength(0);

        // 全て同じ値
        for (let i = 0; i < standardProducts.length; i++) {
            expect(result.products[i].faceCount).toBe(standardProducts[i].faceCount);
        }
    });
});

describe('placedBlockId の保持', () => {
    it('直接コピーでplacedBlockIdは保持されない（新規ID生成）', () => {
        const stdProducts = [
            makeStdProduct('s1', 'p1', 0, 0, 1, 'block-1'),
        ];
        const result = applyDirectCopy(stdProducts);
        // StorePlanogramProductにはplacedBlockIdフィールドがないので問題ない
        expect(result.products[0].productId).toBe('p1');
    });
});

describe('複数段 + 複数ブロック構成の総合テスト', () => {
    const products = [
        makeProduct('p1', '牛肉A', 100, 1),
        makeProduct('p2', '牛肉B', 100, 2),
        makeProduct('p3', '豚肉A', 100, 10),
        makeProduct('p4', '豚肉B', 100, 15),
        makeProduct('p5', '鶏肉A', 100, 20),
    ];

    it('5段棚にブロック3つ、ルールAで段ごとに独立カット', () => {
        const stdProducts: StandardPlanogramProduct[] = [];
        // 5段 x 5商品 = 25商品
        for (let shelf = 0; shelf < 5; shelf++) {
            for (let i = 0; i < 5; i++) {
                stdProducts.push(
                    makeStdProduct(`s${shelf}_${i}`, `p${i + 1}`, shelf, i * 100, 1)
                );
            }
        }
        // 標準幅500mm → ターゲット300mm
        const result = applyRuleA(stdProducts, products, 300);

        // 各段3商品に削減
        for (let shelf = 0; shelf < 5; shelf++) {
            const shelfProducts = result.products.filter(p => p.shelfIndex === shelf);
            expect(shelfProducts.length).toBeLessThanOrEqual(3);

            const shelfWidth = shelfProducts.reduce((sum, sp) => sum + 100 * sp.faceCount, 0);
            expect(shelfWidth).toBeLessThanOrEqual(300);
        }
    });

    it('5段棚にブロック3つ、ルールBで段ごとに独立拡張', () => {
        const stdProducts: StandardPlanogramProduct[] = [];
        for (let shelf = 0; shelf < 5; shelf++) {
            for (let i = 0; i < 3; i++) {
                stdProducts.push(
                    makeStdProduct(`s${shelf}_${i}`, `p${i + 1}`, shelf, i * 100, 1)
                );
            }
        }
        // 標準幅300mm → ターゲット600mm
        const result = applyRuleB(stdProducts, products, 600, 300);

        for (let shelf = 0; shelf < 5; shelf++) {
            const shelfProducts = result.products.filter(p => p.shelfIndex === shelf);
            const shelfWidth = shelfProducts.reduce((sum, sp) => sum + 100 * sp.faceCount, 0);
            expect(shelfWidth).toBeLessThanOrEqual(600);
        }

        // p1(ランク1)は全段で拡張
        const p1Products = result.products.filter(p => p.productId === 'p1');
        expect(p1Products.every(p => p.faceCount >= 2)).toBe(true);
    });
});
