// 商品階層のみで棚ブロック構成 → 標準棚割 → 個店棚割の E2E テスト
import { describe, it, expect } from 'vitest';
import type {
    ShelfBlock,
    HierarchyPlacement,
    StandardPlanogramBlock,
    StandardPlanogramHierarchyPlacement,
    StorePlanogramHierarchyPlacement,
} from '../../data/types';
import { expandBlockHierarchyPlacements } from './standardPlanogramRearrange';

// ================================================================
// ヘルパー
// ================================================================

function makeHierarchyPlacement(
    id: string,
    shelfIndex: number,
    positionX: number,
    width: number,
    faceCount: number = 1,
    overrides: Partial<HierarchyPlacement> = {}
): HierarchyPlacement {
    return {
        id,
        hierarchyLevel: 'department',
        hierarchyCode: `D${id}`,
        hierarchyName: `部門${id}`,
        shelfIndex,
        positionX,
        width,
        faceCount,
        ...overrides,
    };
}

function makeShelfBlock(
    id: string,
    width: number,
    shelfCount: number,
    hierarchyPlacements: HierarchyPlacement[]
): ShelfBlock {
    return {
        id,
        name: `ブロック${id}`,
        width,
        height: 1800,
        shelfCount,
        productPlacements: [],
        hierarchyPlacements,
        createdAt: '',
        updatedAt: '',
    };
}

// 標準棚割データを構築（ブロック配置＋階層展開）
function buildStandardPlanogramWithHierarchy(
    blocks: ShelfBlock[]
): {
    stdBlocks: StandardPlanogramBlock[];
    hierarchyPlacements: StandardPlanogramHierarchyPlacement[];
    totalWidth: number;
} {
    const stdBlocks: StandardPlanogramBlock[] = [];
    const hierarchyPlacements: StandardPlanogramHierarchyPlacement[] = [];
    let posX = 0;

    for (const blk of blocks) {
        const placedBlockId = `pb-${blk.id}`;
        stdBlocks.push({
            id: placedBlockId,
            blockId: blk.id,
            positionX: posX,
            positionY: 0,
        });

        const expanded = expandBlockHierarchyPlacements(
            blk.hierarchyPlacements,
            posX,
            0 // positionY
        );
        for (const eh of expanded) {
            hierarchyPlacements.push({
                ...eh,
                id: `shp-${placedBlockId}-${eh.hierarchyCode}-${eh.shelfIndex}`,
                placedBlockId,
            });
        }

        posX += blk.width;
    }

    return { stdBlocks, hierarchyPlacements, totalWidth: posX };
}

// 個店棚割生成（階層引き継ぎロジック再現）
function generateStorePlanogramHierarchy(
    standardHierarchyPlacements: StandardPlanogramHierarchyPlacement[],
    _storeWidth: number
): StorePlanogramHierarchyPlacement[] {
    // 階層アイテムはカット対象外でそのまま引き継ぎ
    return standardHierarchyPlacements.map(hp => ({
        id: `store-${hp.id}`,
        hierarchyLevel: hp.hierarchyLevel,
        hierarchyCode: hp.hierarchyCode,
        hierarchyName: hp.hierarchyName,
        shelfIndex: hp.shelfIndex,
        positionX: hp.positionX,
        width: hp.width,
        faceCount: hp.faceCount,
        isAutoGenerated: true,
    }));
}

// ================================================================
// シナリオ: 商品階層のみで棚ブロック → 標準棚割 → 個店棚割
// ================================================================

describe('E2E: 商品階層のみの棚ブロック → 標準棚割 → 個店棚割', () => {

    // 精肉売場想定:
    // ブロック1: 牛肉（3段、幅900mm）
    //   段0: 牛肉>こま切れ(300mm) + 牛肉>スライス(300mm) + 牛肉>ステーキ(300mm)
    //   段1: 牛肉>焼肉(450mm×2face)
    //   段2: 牛肉>ブロック(300mm) + 牛肉>ひき肉(300mm)
    // ブロック2: 豚肉（3段、幅600mm）
    //   段0: 豚肉>こま切れ(300mm×2face)
    //   段1: 豚肉>スライス(600mm)
    //   段2: 豚肉>ひき肉(300mm)

    const beefBlock = makeShelfBlock('beef', 900, 3, [
        makeHierarchyPlacement('b-koma', 0, 0, 300, 1, { hierarchyName: '牛肉 > こま切れ', hierarchyCode: 'B-KOMA', hierarchyLevel: 'category' }),
        makeHierarchyPlacement('b-slice', 0, 300, 300, 1, { hierarchyName: '牛肉 > スライス', hierarchyCode: 'B-SLICE', hierarchyLevel: 'category' }),
        makeHierarchyPlacement('b-steak', 0, 600, 300, 1, { hierarchyName: '牛肉 > ステーキ', hierarchyCode: 'B-STEAK', hierarchyLevel: 'category' }),
        makeHierarchyPlacement('b-yakiniku', 1, 0, 450, 2, { hierarchyName: '牛肉 > 焼肉', hierarchyCode: 'B-YAKI', hierarchyLevel: 'category' }),
        makeHierarchyPlacement('b-block', 2, 0, 300, 1, { hierarchyName: '牛肉 > ブロック', hierarchyCode: 'B-BLK', hierarchyLevel: 'category' }),
        makeHierarchyPlacement('b-mince', 2, 300, 300, 1, { hierarchyName: '牛肉 > ひき肉', hierarchyCode: 'B-MINCE', hierarchyLevel: 'category' }),
    ]);

    const porkBlock = makeShelfBlock('pork', 600, 3, [
        makeHierarchyPlacement('p-koma', 0, 0, 300, 2, { hierarchyName: '豚肉 > こま切れ', hierarchyCode: 'P-KOMA', hierarchyLevel: 'category' }),
        makeHierarchyPlacement('p-slice', 1, 0, 600, 1, { hierarchyName: '豚肉 > スライス', hierarchyCode: 'P-SLICE', hierarchyLevel: 'category' }),
        makeHierarchyPlacement('p-mince', 2, 0, 300, 1, { hierarchyName: '豚肉 > ひき肉', hierarchyCode: 'P-MINCE', hierarchyLevel: 'category' }),
    ]);

    describe('Step1: 棚ブロック構成の検証', () => {
        it('牛肉ブロックに商品は0、階層は6配置', () => {
            expect(beefBlock.productPlacements).toHaveLength(0);
            expect(beefBlock.hierarchyPlacements).toHaveLength(6);
        });

        it('豚肉ブロックに商品は0、階層は3配置', () => {
            expect(porkBlock.productPlacements).toHaveLength(0);
            expect(porkBlock.hierarchyPlacements).toHaveLength(3);
        });

        it('牛肉ブロック段0の階層が幅ちょうど900mm', () => {
            const shelf0 = beefBlock.hierarchyPlacements.filter(h => h.shelfIndex === 0);
            const totalWidth = shelf0.reduce((sum, h) => sum + h.width * h.faceCount, 0);
            expect(totalWidth).toBe(900);
        });

        it('牛肉ブロック段1の焼肉は450mm×2face=900mm', () => {
            const yakiniku = beefBlock.hierarchyPlacements.find(h => h.id === 'b-yakiniku')!;
            expect(yakiniku.width * yakiniku.faceCount).toBe(900);
        });

        it('豚肉ブロック段0のこま切れは300mm×2face=600mm', () => {
            const koma = porkBlock.hierarchyPlacements.find(h => h.id === 'p-koma')!;
            expect(koma.width * koma.faceCount).toBe(600);
        });

        it('各段の幅がブロック幅を超えない', () => {
            for (const block of [beefBlock, porkBlock]) {
                for (let si = 0; si < block.shelfCount; si++) {
                    const shelfItems = block.hierarchyPlacements.filter(h => h.shelfIndex === si);
                    const totalWidth = shelfItems.reduce((sum, h) => sum + h.width * h.faceCount, 0);
                    expect(totalWidth).toBeLessThanOrEqual(block.width);
                }
            }
        });
    });

    describe('Step2: 標準棚割への展開', () => {
        const { stdBlocks, hierarchyPlacements, totalWidth } = buildStandardPlanogramWithHierarchy([beefBlock, porkBlock]);

        it('総幅が900+600=1500mm', () => {
            expect(totalWidth).toBe(1500);
        });

        it('ブロックが2つ配置される', () => {
            expect(stdBlocks).toHaveLength(2);
            expect(stdBlocks[0].positionX).toBe(0);
            expect(stdBlocks[1].positionX).toBe(900);
        });

        it('階層アイテムが全9個展開される（牛肉6+豚肉3）', () => {
            expect(hierarchyPlacements).toHaveLength(9);
        });

        it('全階層アイテムにplacedBlockIdが付与される', () => {
            expect(hierarchyPlacements.every(hp => hp.placedBlockId !== undefined)).toBe(true);
        });

        it('牛肉階層のplacedBlockIdが牛肉ブロックを指す', () => {
            const beefHierarchies = hierarchyPlacements.filter(hp => hp.hierarchyCode.startsWith('B-'));
            expect(beefHierarchies).toHaveLength(6);
            expect(beefHierarchies.every(hp => hp.placedBlockId === 'pb-beef')).toBe(true);
        });

        it('豚肉階層のplacedBlockIdが豚肉ブロックを指す', () => {
            const porkHierarchies = hierarchyPlacements.filter(hp => hp.hierarchyCode.startsWith('P-'));
            expect(porkHierarchies).toHaveLength(3);
            expect(porkHierarchies.every(hp => hp.placedBlockId === 'pb-pork')).toBe(true);
        });

        it('豚肉階層のpositionXが牛肉ブロック幅(900mm)分オフセットされている', () => {
            const porkHierarchies = hierarchyPlacements.filter(hp => hp.hierarchyCode.startsWith('P-'));
            expect(porkHierarchies.every(hp => hp.positionX >= 900)).toBe(true);
        });

        it('牛肉ブロック段0の3カテゴリが正しいpositionXで展開', () => {
            const koma = hierarchyPlacements.find(hp => hp.hierarchyCode === 'B-KOMA')!;
            const slice = hierarchyPlacements.find(hp => hp.hierarchyCode === 'B-SLICE')!;
            const steak = hierarchyPlacements.find(hp => hp.hierarchyCode === 'B-STEAK')!;
            expect(koma.positionX).toBe(0);
            expect(slice.positionX).toBe(300);
            expect(steak.positionX).toBe(600);
            expect(koma.shelfIndex).toBe(0);
        });

        it('牛肉ブロック段1の焼肉が正しく展開', () => {
            const yaki = hierarchyPlacements.find(hp => hp.hierarchyCode === 'B-YAKI')!;
            expect(yaki.positionX).toBe(0);
            expect(yaki.shelfIndex).toBe(1);
            expect(yaki.width).toBe(450);
            expect(yaki.faceCount).toBe(2);
        });

        it('豚肉ブロック段1のスライスが正しくオフセット展開', () => {
            const pSlice = hierarchyPlacements.find(hp => hp.hierarchyCode === 'P-SLICE')!;
            expect(pSlice.positionX).toBe(900); // 牛肉ブロック900mm + 段内位置0
            expect(pSlice.shelfIndex).toBe(1);
            expect(pSlice.width).toBe(600);
        });

        it('商品は0件（階層のみ構成）', () => {
            // 標準棚割の商品は空
            const stdProducts: any[] = [];
            expect(stdProducts).toHaveLength(0);
        });
    });

    describe('Step3: 個店棚割生成（階層引き継ぎ）', () => {
        const { hierarchyPlacements: stdHierarchies } = buildStandardPlanogramWithHierarchy([beefBlock, porkBlock]);

        it('店舗棚幅 = 標準幅 → そのままコピー', () => {
            const storeHierarchies = generateStorePlanogramHierarchy(stdHierarchies, 1500);
            expect(storeHierarchies).toHaveLength(9);
            // 全てisAutoGenerated=true
            expect(storeHierarchies.every(h => h.isAutoGenerated)).toBe(true);
        });

        it('店舗棚幅 < 標準幅 でも階層はカットされない', () => {
            const storeHierarchies = generateStorePlanogramHierarchy(stdHierarchies, 1200);
            // 階層アイテムはカット対象外
            expect(storeHierarchies).toHaveLength(9);
        });

        it('店舗棚幅 > 標準幅 でも階層はそのまま引き継ぎ', () => {
            const storeHierarchies = generateStorePlanogramHierarchy(stdHierarchies, 2400);
            expect(storeHierarchies).toHaveLength(9);
        });

        it('階層コード・名前・レベルが正しく引き継がれる', () => {
            const storeHierarchies = generateStorePlanogramHierarchy(stdHierarchies, 1500);
            const koma = storeHierarchies.find(h => h.hierarchyCode === 'B-KOMA')!;
            expect(koma.hierarchyName).toBe('牛肉 > こま切れ');
            expect(koma.hierarchyLevel).toBe('category');
            expect(koma.positionX).toBe(0);
            expect(koma.shelfIndex).toBe(0);
            expect(koma.width).toBe(300);
            expect(koma.faceCount).toBe(1);
        });

        it('フェイス数が正しく引き継がれる', () => {
            const storeHierarchies = generateStorePlanogramHierarchy(stdHierarchies, 1500);
            const yaki = storeHierarchies.find(h => h.hierarchyCode === 'B-YAKI')!;
            expect(yaki.faceCount).toBe(2);
            expect(yaki.width).toBe(450);
        });

        it('豚肉階層の位置がオフセット付きで引き継がれる', () => {
            const storeHierarchies = generateStorePlanogramHierarchy(stdHierarchies, 1500);
            const pKoma = storeHierarchies.find(h => h.hierarchyCode === 'P-KOMA')!;
            expect(pKoma.positionX).toBe(900);
            expect(pKoma.width).toBe(300);
            expect(pKoma.faceCount).toBe(2);
        });
    });

    describe('Step4: 全体の整合性検証', () => {
        const { hierarchyPlacements: stdHierarchies, totalWidth } = buildStandardPlanogramWithHierarchy([beefBlock, porkBlock]);
        const storeHierarchies = generateStorePlanogramHierarchy(stdHierarchies, totalWidth);

        it('棚ブロック → 標準棚割 → 個店棚割で階層数が一貫する', () => {
            const blockTotal = beefBlock.hierarchyPlacements.length + porkBlock.hierarchyPlacements.length;
            expect(blockTotal).toBe(9);
            expect(stdHierarchies).toHaveLength(9);
            expect(storeHierarchies).toHaveLength(9);
        });

        it('全段で階層アイテムの重なりがない', () => {
            for (let si = 0; si < 3; si++) {
                const items = stdHierarchies
                    .filter(h => h.shelfIndex === si)
                    .sort((a, b) => a.positionX - b.positionX);

                for (let i = 0; i < items.length - 1; i++) {
                    const currentEnd = items[i].positionX + items[i].width * items[i].faceCount;
                    expect(currentEnd).toBeLessThanOrEqual(items[i + 1].positionX);
                }
            }
        });

        it('個店棚割でも全段の重なりがない', () => {
            for (let si = 0; si < 3; si++) {
                const items = storeHierarchies
                    .filter(h => h.shelfIndex === si)
                    .sort((a, b) => a.positionX - b.positionX);

                for (let i = 0; i < items.length - 1; i++) {
                    const currentEnd = items[i].positionX + items[i].width * items[i].faceCount;
                    expect(currentEnd).toBeLessThanOrEqual(items[i + 1].positionX);
                }
            }
        });

        it('標準棚割と個店棚割で同一のhierarchyCodeセットを持つ', () => {
            const stdCodes = new Set(stdHierarchies.map(h => h.hierarchyCode));
            const storeCodes = new Set(storeHierarchies.map(h => h.hierarchyCode));
            expect(stdCodes).toEqual(storeCodes);
        });

        it('全階層の位置・幅・フェイス数が標準→個店で保持される', () => {
            for (const sh of stdHierarchies) {
                const store = storeHierarchies.find(h => h.hierarchyCode === sh.hierarchyCode && h.shelfIndex === sh.shelfIndex)!;
                expect(store).toBeDefined();
                expect(store.positionX).toBe(sh.positionX);
                expect(store.width).toBe(sh.width);
                expect(store.faceCount).toBe(sh.faceCount);
                expect(store.hierarchyName).toBe(sh.hierarchyName);
                expect(store.hierarchyLevel).toBe(sh.hierarchyLevel);
            }
        });
    });
});

// ================================================================
// シナリオ: 複数階層レベル混在ブロック
// ================================================================

describe('E2E: 異なる階層レベルが混在する棚ブロック', () => {
    // 部門レベルとカテゴリレベルを混在
    const mixedBlock = makeShelfBlock('mixed', 900, 2, [
        makeHierarchyPlacement('dept-beef', 0, 0, 450, 1, {
            hierarchyLevel: 'department', hierarchyCode: 'DEPT-BEEF', hierarchyName: '牛肉',
        }),
        makeHierarchyPlacement('cat-pork-koma', 0, 450, 450, 1, {
            hierarchyLevel: 'category', hierarchyCode: 'CAT-P-KOMA', hierarchyName: '豚肉 > こま切れ',
        }),
        makeHierarchyPlacement('seg-chicken', 1, 0, 300, 3, {
            hierarchyLevel: 'segment', hierarchyCode: 'SEG-CHICK', hierarchyName: '鶏肉 > もも > 唐揚げ用',
        }),
    ]);

    it('異なる階層レベルが共存できる', () => {
        const levels = mixedBlock.hierarchyPlacements.map(h => h.hierarchyLevel);
        expect(levels).toEqual(['department', 'category', 'segment']);
    });

    it('標準棚割に正しく展開される', () => {
        const { hierarchyPlacements } = buildStandardPlanogramWithHierarchy([mixedBlock]);
        expect(hierarchyPlacements).toHaveLength(3);

        const dept = hierarchyPlacements.find(h => h.hierarchyLevel === 'department')!;
        expect(dept.hierarchyName).toBe('牛肉');
        expect(dept.positionX).toBe(0);

        const cat = hierarchyPlacements.find(h => h.hierarchyLevel === 'category')!;
        expect(cat.hierarchyName).toBe('豚肉 > こま切れ');
        expect(cat.positionX).toBe(450);

        const seg = hierarchyPlacements.find(h => h.hierarchyLevel === 'segment')!;
        expect(seg.hierarchyName).toBe('鶏肉 > もも > 唐揚げ用');
        expect(seg.faceCount).toBe(3);
        expect(seg.width * seg.faceCount).toBe(900);
    });

    it('個店棚割でレベル情報が保持される', () => {
        const { hierarchyPlacements: stdH } = buildStandardPlanogramWithHierarchy([mixedBlock]);
        const storeH = generateStorePlanogramHierarchy(stdH, 900);
        expect(storeH.find(h => h.hierarchyLevel === 'department')).toBeDefined();
        expect(storeH.find(h => h.hierarchyLevel === 'category')).toBeDefined();
        expect(storeH.find(h => h.hierarchyLevel === 'segment')).toBeDefined();
    });
});

// ================================================================
// シナリオ: 空ブロック（階層なし）との混在
// ================================================================

describe('E2E: 階層ブロックと空ブロックの混在', () => {
    const hierBlock = makeShelfBlock('hier', 600, 2, [
        makeHierarchyPlacement('h1', 0, 0, 300, 2, { hierarchyName: '牛肉 > こま切れ', hierarchyCode: 'H1' }),
        makeHierarchyPlacement('h2', 1, 0, 600, 1, { hierarchyName: '牛肉 > スライス', hierarchyCode: 'H2' }),
    ]);
    const emptyBlock = makeShelfBlock('empty', 300, 2, []);

    it('空ブロックからは階層が展開されない', () => {
        const { hierarchyPlacements } = buildStandardPlanogramWithHierarchy([hierBlock, emptyBlock]);
        expect(hierarchyPlacements).toHaveLength(2);
        expect(hierarchyPlacements.every(h => h.placedBlockId === 'pb-hier')).toBe(true);
    });

    it('総幅が正しく計算される', () => {
        const { totalWidth } = buildStandardPlanogramWithHierarchy([hierBlock, emptyBlock]);
        expect(totalWidth).toBe(900);
    });
});
