// ユーザーワークフロー受け入れテスト
// 実際にユーザーがやりたいことのシナリオをテストする
import { describe, it, expect } from 'vitest';
import type {
    StandardPlanogramBlock,
    StandardPlanogramProduct,
    ProductPlacement,
    Product,
    StorePlanogramProduct,
} from '../../data/types';
import {
    expandBlockProducts,
    swapBlock,
} from './standardPlanogramRearrange';
import type { BlockMasterMap } from './standardPlanogramRearrange';

// ================================================================
// ヘルパー
// ================================================================

function makeProduct(id: string, name: string, width: number, salesRank: number, dept: string): Product {
    return { id, name, jan: `4900${id}`, width, height: 200, depth: 100, salesRank, category: '', imageUrl: '', departmentName: dept, createdAt: '', updatedAt: '' } as Product;
}

function pl(productId: string, shelfIndex: number, positionX: number, faceCount: number): ProductPlacement {
    return { id: `pl-${productId}-${shelfIndex}`, productId, shelfIndex, positionX, faceCount };
}

function block(id: string, blockId: string, posX: number, posY: number): StandardPlanogramBlock {
    return { id, blockId, positionX: posX, positionY: posY };
}

// ルールA(カット)再現
function applyRuleA(
    products: StandardPlanogramProduct[],
    productMaster: Product[],
    targetWidth: number
): { products: StorePlanogramProduct[]; warnings: string[] } {
    const warnings: string[] = [];
    const sortedProducts = [...products].sort((a, b) => {
        const prodA = productMaster.find(p => p.id === a.productId);
        const prodB = productMaster.find(p => p.id === b.productId);
        return (prodB?.salesRank || 100) - (prodA?.salesRank || 100);
    });
    const result: StorePlanogramProduct[] = [];
    const shelfIndices = [...new Set(sortedProducts.map(p => p.shelfIndex))];

    for (const shelfIndex of shelfIndices) {
        let shelfProducts = sortedProducts.filter(p => p.shelfIndex === shelfIndex);
        let currentWidth = 0;
        for (const sp of shelfProducts) {
            const product = productMaster.find(p => p.id === sp.productId);
            if (!product) continue;
            currentWidth += product.width * sp.faceCount;
        }
        while (currentWidth > targetWidth && shelfProducts.length > 0) {
            const worstProduct = shelfProducts[0];
            const product = productMaster.find(p => p.id === worstProduct.productId);
            if (!product) { shelfProducts = shelfProducts.slice(1); continue; }
            if (worstProduct.faceCount > 1) {
                worstProduct.faceCount -= 1;
                currentWidth -= product.width;
                warnings.push(`${product.name}: フェイス削減`);
            } else {
                shelfProducts = shelfProducts.slice(1);
                currentWidth -= product.width;
                warnings.push(`${product.name}: カット`);
            }
        }
        let posX = 0;
        for (const sp of shelfProducts) {
            const product = productMaster.find(p => p.id === sp.productId);
            if (!product) continue;
            result.push({ id: `g-${sp.id}`, productId: sp.productId, shelfIndex, positionX: posX, faceCount: sp.faceCount, isAutoGenerated: true, isCut: false });
            posX += product.width * sp.faceCount;
        }
    }
    return { products: result, warnings };
}

// ルールB(拡張)再現
function applyRuleB(
    products: StandardPlanogramProduct[],
    productMaster: Product[],
    targetWidth: number
): { products: StorePlanogramProduct[]; warnings: string[] } {
    const warnings: string[] = [];
    const ranked = products.map(p => ({ ...p, salesRank: productMaster.find(pm => pm.id === p.productId)?.salesRank || 100 }))
        .sort((a, b) => a.salesRank - b.salesRank).slice(0, 10);
    const top10Ids = new Set(ranked.map(p => p.productId));
    const shelfIndices = [...new Set(products.map(p => p.shelfIndex))];
    const result: StorePlanogramProduct[] = [];

    for (const shelfIndex of shelfIndices) {
        const shelfProducts = products.filter(p => p.shelfIndex === shelfIndex).map(p => ({ ...p }));
        let currentUsed = 0;
        for (const sp of shelfProducts) {
            const product = productMaster.find(p => p.id === sp.productId);
            if (product) currentUsed += product.width * sp.faceCount;
        }
        for (const sp of shelfProducts) {
            if (!top10Ids.has(sp.productId)) continue;
            const product = productMaster.find(p => p.id === sp.productId);
            if (!product) continue;
            const extraNeeded = product.width * sp.faceCount;
            if (targetWidth - currentUsed >= extraNeeded) {
                const old = sp.faceCount;
                sp.faceCount = old * 2;
                currentUsed += product.width * old;
                warnings.push(`${product.name}: 2倍`);
            }
        }
        let posX = 0;
        for (const sp of shelfProducts) {
            const product = productMaster.find(p => p.id === sp.productId);
            if (!product) continue;
            result.push({ id: `g-${sp.id}`, productId: sp.productId, shelfIndex, positionX: posX, faceCount: sp.faceCount, isAutoGenerated: true, isCut: false });
            posX += product.width * sp.faceCount;
        }
    }
    return { products: result, warnings };
}

// buildStandardPlanogramData再現
function buildStandardPlanogramData(
    blocks: { id: string; width: number; shelfCount: number; productPlacements: ProductPlacement[] }[]
) {
    const stdBlocks: StandardPlanogramBlock[] = [];
    const stdProducts: StandardPlanogramProduct[] = [];
    let posX = 0;

    for (const blk of blocks) {
        const placedBlockId = `pb-${blk.id}`;
        stdBlocks.push({ id: placedBlockId, blockId: blk.id, positionX: posX, positionY: 0 });
        for (const pl of blk.productPlacements) {
            stdProducts.push({
                id: `sp-${placedBlockId}-${pl.productId}-${pl.shelfIndex}`,
                productId: pl.productId,
                shelfIndex: pl.shelfIndex,
                positionX: posX + pl.positionX,
                faceCount: pl.faceCount,
                placedBlockId,
            });
        }
        posX += blk.width;
    }
    return { blocks: stdBlocks, products: stdProducts, totalWidth: posX };
}

// findBlockForProduct再現（placedBlockId優先）
function findBlockForProduct(
    sp: StandardPlanogramProduct,
    sortedBlocks: StandardPlanogramBlock[],
    blockMasters: { id: string; width: number; shelfCount: number }[]
): { placedBlockId: string; blockId: string } | null {
    if (sp.placedBlockId) {
        const pb = sortedBlocks.find(b => b.id === sp.placedBlockId);
        if (pb) return { placedBlockId: pb.id, blockId: pb.blockId };
    }
    // フォールバック: 位置ベース
    for (const pb of sortedBlocks) {
        const master = blockMasters.find(b => b.id === pb.blockId);
        if (!master) continue;
        const inXRange = sp.positionX >= pb.positionX - 0.1 && sp.positionX < pb.positionX + master.width + 0.1;
        const inYRange = sp.shelfIndex >= pb.positionY && sp.shelfIndex < pb.positionY + master.shelfCount;
        if (inXRange && inYRange) return { placedBlockId: pb.id, blockId: pb.blockId };
    }
    return null;
}

// ================================================================
// シナリオ1: 棚ブロックを配置して標準棚割を作る
// ================================================================

describe('シナリオ1: 標準棚割にブロックを配置 → 商品が正しく展開される', () => {
    const beefProducts: ProductPlacement[] = [
        pl('beef1', 0, 0, 3),
        pl('beef2', 0, 390, 3),
        pl('beef1', 1, 0, 3),
        pl('beef2', 1, 390, 3),
    ];
    const porkProducts: ProductPlacement[] = [
        pl('pork1', 0, 0, 2),
        pl('pork1', 1, 0, 2),
    ];

    const beefBlock = { id: 'blk-beef', width: 750, shelfCount: 2, productPlacements: beefProducts };
    const porkBlock = { id: 'blk-pork', width: 240, shelfCount: 2, productPlacements: porkProducts };

    it('全商品にplacedBlockIdが付与される', () => {
        const { products } = buildStandardPlanogramData([beefBlock, porkBlock]);
        expect(products.every(p => p.placedBlockId !== undefined)).toBe(true);
    });

    it('各商品のplacedBlockIdが正しいブロックを指す', () => {
        const { blocks, products } = buildStandardPlanogramData([beefBlock, porkBlock]);

        const beefPlaced = products.filter(p => p.productId.startsWith('beef'));
        const porkPlaced = products.filter(p => p.productId.startsWith('pork'));

        // 牛肉商品は全て牛肉ブロックのplacedBlockId
        expect(beefPlaced.every(p => p.placedBlockId === blocks[0].id)).toBe(true);
        // 豚肉商品は全て豚肉ブロックのplacedBlockId
        expect(porkPlaced.every(p => p.placedBlockId === blocks[1].id)).toBe(true);
    });

    it('商品のpositionXがブロックのオフセット分ずれている', () => {
        const { products } = buildStandardPlanogramData([beefBlock, porkBlock]);

        // 豚肉ブロックの商品は牛肉ブロック幅(750mm)分ずれる
        const porkPlaced = products.filter(p => p.productId === 'pork1');
        expect(porkPlaced.every(p => p.positionX >= 750)).toBe(true);
    });

    it('商品数がブロック内の配置数と一致する', () => {
        const { products } = buildStandardPlanogramData([beefBlock, porkBlock]);
        expect(products).toHaveLength(beefProducts.length + porkProducts.length);
    });
});

// ================================================================
// シナリオ2: ブロッククリックで所属商品を強調表示
// ================================================================

describe('シナリオ2: ブロッククリック → 所属商品の強調表示が正しい', () => {
    const beefBlock = {
        id: 'blk-beef', width: 900, shelfCount: 5,
        productPlacements: [
            pl('beef1', 0, 0, 3),
            pl('beef2', 1, 0, 2),
        ],
    };
    const porkBlock = {
        id: 'blk-pork', width: 900, shelfCount: 5,
        productPlacements: [
            pl('pork1', 0, 0, 3),
            pl('pork2', 1, 0, 2),
        ],
    };

    it('placedBlockIdにより正しいブロックに割り当てられる', () => {
        const { blocks, products } = buildStandardPlanogramData([beefBlock, porkBlock]);
        const masters = [
            { id: 'blk-beef', width: 900, shelfCount: 5 },
            { id: 'blk-pork', width: 900, shelfCount: 5 },
        ];

        // 牛肉ブロック選択時
        const selectedBlockId = blocks[0].id; // pb-blk-beef
        for (const sp of products) {
            const info = findBlockForProduct(sp, blocks, masters);
            const belongsToSelected = info?.placedBlockId === selectedBlockId;

            if (sp.productId.startsWith('beef')) {
                expect(belongsToSelected).toBe(true);  // 牛肉 → 強調
            } else {
                expect(belongsToSelected).toBe(false);  // 豚肉 → dimmed
            }
        }
    });

    it('placedBlockIdがない場合は位置ベースでフォールバック（境界の誤判定あり）', () => {
        const { blocks, products } = buildStandardPlanogramData([beefBlock, porkBlock]);
        const masters = [
            { id: 'blk-beef', width: 900, shelfCount: 5 },
            { id: 'blk-pork', width: 900, shelfCount: 5 },
        ];

        // placedBlockIdを消す
        const productsWithoutBlockId = products.map(p => ({ ...p, placedBlockId: undefined }));

        // 位置ベースでは境界上（positionX=900、ブロック幅900）の商品が前のブロックにマッチしうる
        // → placedBlockIdがないと誤判定する。これがplacedBlockIdが必要な理由
        const beefProds = productsWithoutBlockId.filter(p => p.productId.startsWith('beef'));
        for (const sp of beefProds) {
            const info = findBlockForProduct(sp, blocks, masters);
            expect(info).not.toBeNull();
            expect(info!.blockId).toBe('blk-beef');
        }

        // pork商品はpositionX=900で、beefブロック(0~900)の境界上
        // 位置ベースだと < 900.1 の判定でbeefにマッチしてしまう
        const porkProds = productsWithoutBlockId.filter(p => p.productId.startsWith('pork'));
        for (const sp of porkProds) {
            const info = findBlockForProduct(sp, blocks, masters);
            expect(info).not.toBeNull();
            // 位置ベースでは誤ってblk-beefにマッチする（これがplacedBlockIdの必要性を示す）
            expect(info!.blockId).toBe('blk-beef'); // 意図しない結果だがplacedBlockIdなしの限界
        }
    });

    it('位置ベースでは誤判定するケースをplacedBlockIdで正しく判定', () => {
        // ブロック幅が実際の商品配置幅より大きい場合、位置ベースだと隣のブロック商品を含んでしまう
        const wideBlock = {
            id: 'blk-wide', width: 1200, shelfCount: 5, // 幅1200だが商品は900mm分しかない
            productPlacements: [
                pl('w1', 0, 0, 1),
            ],
        };
        const nextBlock = {
            id: 'blk-next', width: 600, shelfCount: 5,
            productPlacements: [
                pl('n1', 0, 0, 1),
            ],
        };

        const { blocks, products } = buildStandardPlanogramData([wideBlock, nextBlock]);
        const masters = [
            { id: 'blk-wide', width: 1200, shelfCount: 5 },
            { id: 'blk-next', width: 600, shelfCount: 5 },
        ];

        // n1はpositionX=1200で、wideBlockの範囲(0~1200)の境界上
        // placedBlockIdがあるのでblk-nextに正しく割り当てられる
        const n1 = products.find(p => p.productId === 'n1')!;
        const info = findBlockForProduct(n1, blocks, masters);
        expect(info!.blockId).toBe('blk-next');
    });
});

// ================================================================
// シナリオ3: ブロック入れ替え後も色（ブロック紐づけ）が正しい
// ================================================================

describe('シナリオ3: ブロック入れ替え → 色区分が棚ブロックに紐づいて変わらない', () => {
    const masters: BlockMasterMap = [
        { id: 'blk-beef', width: 900, shelfCount: 5 },
        { id: 'blk-pork', width: 900, shelfCount: 5 },
        { id: 'blk-chicken', width: 600, shelfCount: 5 },
    ];

    // 色はsorted unique blockIdで決まる
    function getBlockColorMap(blocks: StandardPlanogramBlock[]): Map<string, number> {
        const uniqueBlockIds = [...new Set(blocks.map(pb => pb.blockId))].sort();
        const map = new Map<string, number>();
        uniqueBlockIds.forEach((blockId, i) => map.set(blockId, i));
        return map;
    }

    it('入れ替え前後でblockIdごとの色インデックスが同じ', () => {
        const blocks = [
            block('pb1', 'blk-beef', 0, 0),
            block('pb2', 'blk-pork', 900, 0),
            block('pb3', 'blk-chicken', 1800, 0),
        ];

        const colorBefore = getBlockColorMap(blocks);

        // 牛肉と豚肉を入れ替え
        const swapped = swapBlock(blocks, 'pb1', 'right', masters, 2400, 5);
        expect(swapped).not.toBeNull();

        const colorAfter = getBlockColorMap(swapped!);

        // 各blockIdの色インデックスが同じ
        expect(colorAfter.get('blk-beef')).toBe(colorBefore.get('blk-beef'));
        expect(colorAfter.get('blk-pork')).toBe(colorBefore.get('blk-pork'));
        expect(colorAfter.get('blk-chicken')).toBe(colorBefore.get('blk-chicken'));
    });

    it('入れ替え後にplacedBlockIdで再展開しても商品のブロック所属は正しい', () => {
        const blocks = [
            block('pb1', 'blk-beef', 0, 0),
            block('pb2', 'blk-pork', 900, 0),
        ];

        const beefPlacements: ProductPlacement[] = [
            pl('beef1', 0, 0, 3),
        ];
        const porkPlacements: ProductPlacement[] = [
            pl('pork1', 0, 0, 2),
        ];

        // 入れ替え
        const swapped = swapBlock(blocks, 'pb1', 'right', masters, 1800, 5)!;
        expect(swapped).not.toBeNull();

        // 入れ替え後、各ブロックの商品を再展開しplacedBlockIdを付与
        const allProducts: StandardPlanogramProduct[] = [];
        for (const pb of swapped) {
            const placements = pb.blockId === 'blk-beef' ? beefPlacements : porkPlacements;
            const expanded = expandBlockProducts(placements, new Set(['beef1', 'pork1']), pb.positionX, pb.positionY);
            for (const ep of expanded) {
                allProducts.push({ ...ep, id: `sp-${pb.id}`, placedBlockId: pb.id });
            }
        }

        // beef1はblk-beefブロック（pb1）に紐づいている
        const beef1 = allProducts.find(p => p.productId === 'beef1')!;
        const beef1Block = swapped.find(b => b.id === beef1.placedBlockId)!;
        expect(beef1Block.blockId).toBe('blk-beef');

        // pork1はblk-porkブロック（pb2）に紐づいている
        const pork1 = allProducts.find(p => p.productId === 'pork1')!;
        const pork1Block = swapped.find(b => b.id === pork1.placedBlockId)!;
        expect(pork1Block.blockId).toBe('blk-pork');
    });
});

// ================================================================
// シナリオ4: 標準棚割 → 個店棚割 自動展開
// ================================================================

describe('シナリオ4: 標準棚割 → 個店棚割 自動展開', () => {
    const products: Product[] = [
        makeProduct('beef1', '国産牛テール', 130, 1, '牛肉'),
        makeProduct('beef2', '国産牛切り落とし', 120, 2, '牛肉'),
        makeProduct('pork1', '国産豚バラ薄切り', 120, 10, '豚肉'),
        makeProduct('pork2', '国産豚こま切れ', 110, 15, '豚肉'),
        makeProduct('chicken1', '鶏もも肉', 130, 20, '鶏肉'),
    ];

    // 標準棚割: 5段、幅3600mm（12尺）
    const stdProducts: StandardPlanogramProduct[] = [];
    for (let shelf = 0; shelf < 5; shelf++) {
        let posX = 0;
        for (const prod of products) {
            stdProducts.push({
                id: `std-${shelf}-${prod.id}`,
                productId: prod.id,
                shelfIndex: shelf,
                positionX: posX,
                faceCount: 3,
            });
            posX += prod.width * 3;
        }
    }
    void products.reduce((sum, p) => sum + p.width * 3, 0); // 1830mm per shelf

    it('大型店舗(80尺): ルールBで全商品残り、上位商品が拡張', () => {
        const storeWidth = 24000; // 80尺
        const result = applyRuleB(stdProducts, products, storeWidth);

        // 全商品が残っている
        for (const prod of products) {
            expect(result.products.some(p => p.productId === prod.id)).toBe(true);
        }

        // 上位商品(beef1, ランク1)が拡張されている
        const beef1 = result.products.filter(p => p.productId === 'beef1');
        expect(beef1.some(p => p.faceCount > 3)).toBe(true);
    });

    it('小型店舗(32尺): ルールAでランク下位がカットされる', () => {
        const storeWidth = 1200; // 非常に小さい
        const result = applyRuleA(stdProducts, products, storeWidth);

        // ランク1(beef1)は残っている
        expect(result.products.some(p => p.productId === 'beef1')).toBe(true);

        // 各段の幅がstoreWidth以下
        for (let shelf = 0; shelf < 5; shelf++) {
            const shelfProds = result.products.filter(p => p.shelfIndex === shelf);
            const shelfWidth = shelfProds.reduce((sum, sp) => {
                const prod = products.find(p => p.id === sp.productId)!;
                return sum + prod.width * sp.faceCount;
            }, 0);
            expect(shelfWidth).toBeLessThanOrEqual(storeWidth);
        }
    });

    it('同型店舗: 全商品が1:1コピー', () => {
        const result = {
            products: stdProducts.map(p => ({
                id: `g-${p.id}`, productId: p.productId, shelfIndex: p.shelfIndex,
                positionX: p.positionX, faceCount: p.faceCount, isAutoGenerated: true, isCut: false,
            })),
            warnings: [] as string[],
        };

        expect(result.products).toHaveLength(stdProducts.length);
        for (let i = 0; i < stdProducts.length; i++) {
            expect(result.products[i].faceCount).toBe(stdProducts[i].faceCount);
        }
    });

    it('個店棚割で商品の重複がない', () => {
        const storeWidth = 24000;
        const result = applyRuleB(stdProducts, products, storeWidth);

        // 各段内で同じpositionXに2商品が重ならない
        for (let shelf = 0; shelf < 5; shelf++) {
            const shelfProds = result.products.filter(p => p.shelfIndex === shelf);
            const positions = shelfProds.map(p => p.positionX);
            const uniquePositions = new Set(positions);
            expect(uniquePositions.size).toBe(positions.length);
        }
    });

    it('個店棚割で商品間に不正な隙間がない', () => {
        const storeWidth = 24000;
        const result = applyRuleB(stdProducts, products, storeWidth);

        for (let shelf = 0; shelf < 5; shelf++) {
            const shelfProds = result.products
                .filter(p => p.shelfIndex === shelf)
                .sort((a, b) => a.positionX - b.positionX);

            for (let i = 0; i < shelfProds.length - 1; i++) {
                const prod = products.find(p => p.id === shelfProds[i].productId)!;
                const expectedNextX = shelfProds[i].positionX + prod.width * shelfProds[i].faceCount;
                expect(shelfProds[i + 1].positionX).toBe(expectedNextX);
            }
        }
    });
});

// ================================================================
// シナリオ5: ダミーデータの整合性
// ================================================================

describe('シナリオ5: buildStandardPlanogramDataの整合性', () => {
    it('ブロック幅の合計とtotalWidthが一致', () => {
        const blocks = [
            { id: 'a', width: 3600, shelfCount: 5, productPlacements: [] as ProductPlacement[] },
            { id: 'b', width: 2400, shelfCount: 5, productPlacements: [] as ProductPlacement[] },
            { id: 'c', width: 1800, shelfCount: 5, productPlacements: [] as ProductPlacement[] },
        ];
        const { totalWidth } = buildStandardPlanogramData(blocks);
        expect(totalWidth).toBe(3600 + 2400 + 1800);
    });

    it('全商品のpositionXがブロック範囲内', () => {
        const blocks = [
            {
                id: 'a', width: 600, shelfCount: 2,
                productPlacements: [
                    pl('p1', 0, 0, 1),
                    pl('p2', 0, 100, 1),
                ],
            },
            {
                id: 'b', width: 400, shelfCount: 2,
                productPlacements: [
                    pl('p3', 0, 0, 1),
                ],
            },
        ];
        const { blocks: stdBlocks, products } = buildStandardPlanogramData(blocks);

        for (const sp of products) {
            const pb = stdBlocks.find(b => b.id === sp.placedBlockId)!;
            const blk = blocks.find(b => `pb-${b.id}` === pb.id)!;
            // 商品のpositionXがブロックの範囲内
            expect(sp.positionX).toBeGreaterThanOrEqual(pb.positionX);
            expect(sp.positionX).toBeLessThan(pb.positionX + blk.width);
        }
    });

    it('ブロック間でplacedBlockIdが正しく分離している', () => {
        const blocks = [
            {
                id: 'a', width: 300, shelfCount: 1,
                productPlacements: [pl('p1', 0, 0, 1)],
            },
            {
                id: 'b', width: 300, shelfCount: 1,
                productPlacements: [pl('p2', 0, 0, 1)],
            },
        ];
        const { blocks: stdBlocks, products } = buildStandardPlanogramData(blocks);

        const p1 = products.find(p => p.productId === 'p1')!;
        const p2 = products.find(p => p.productId === 'p2')!;
        expect(p1.placedBlockId).not.toBe(p2.placedBlockId);
        expect(p1.placedBlockId).toBe(stdBlocks[0].id);
        expect(p2.placedBlockId).toBe(stdBlocks[1].id);
    });
});

// ================================================================
// シナリオ6: 縦積みブロック構成での強調表示
// ================================================================

describe('シナリオ6: 縦積みブロック → 正しいブロック強調', () => {
    it('同じX位置で段が異なるブロック、placedBlockIdで正しく判別', () => {
        const blockA = {
            id: 'blk-lower', width: 900, shelfCount: 2,
            productPlacements: [
                pl('p1', 0, 0, 1),
                pl('p2', 1, 0, 1),
            ],
        };
        const blockB = {
            id: 'blk-upper', width: 900, shelfCount: 3,
            productPlacements: [
                pl('p3', 0, 0, 1),
                pl('p4', 1, 0, 1),
                pl('p5', 2, 0, 1),
            ],
        };

        // 手動で縦積み構築（positionY=0とpositionY=2）
        const pbLower: StandardPlanogramBlock = { id: 'pb-lower', blockId: 'blk-lower', positionX: 0, positionY: 0 };
        const pbUpper: StandardPlanogramBlock = { id: 'pb-upper', blockId: 'blk-upper', positionX: 0, positionY: 2 };

        const allProducts: StandardPlanogramProduct[] = [];

        // lower: shelfIndex 0,1
        for (const pl of blockA.productPlacements) {
            allProducts.push({
                id: `sp-${pl.productId}`,
                productId: pl.productId,
                shelfIndex: pl.shelfIndex + 0, // positionY=0
                positionX: pl.positionX,
                faceCount: pl.faceCount,
                placedBlockId: 'pb-lower',
            });
        }
        // upper: shelfIndex 2,3,4
        for (const pl of blockB.productPlacements) {
            allProducts.push({
                id: `sp-${pl.productId}`,
                productId: pl.productId,
                shelfIndex: pl.shelfIndex + 2, // positionY=2
                positionX: pl.positionX,
                faceCount: pl.faceCount,
                placedBlockId: 'pb-upper',
            });
        }

        const blocks = [pbLower, pbUpper];
        const masters = [
            { id: 'blk-lower', width: 900, shelfCount: 2 },
            { id: 'blk-upper', width: 900, shelfCount: 3 },
        ];

        // 下段ブロック選択時
        const selectedLower = 'pb-lower';
        for (const sp of allProducts) {
            const info = findBlockForProduct(sp, blocks, masters);
            const belongs = info?.placedBlockId === selectedLower;
            if (['p1', 'p2'].includes(sp.productId)) {
                expect(belongs).toBe(true);
            } else {
                expect(belongs).toBe(false);
            }
        }

        // 上段ブロック選択時
        const selectedUpper = 'pb-upper';
        for (const sp of allProducts) {
            const info = findBlockForProduct(sp, blocks, masters);
            const belongs = info?.placedBlockId === selectedUpper;
            if (['p3', 'p4', 'p5'].includes(sp.productId)) {
                expect(belongs).toBe(true);
            } else {
                expect(belongs).toBe(false);
            }
        }
    });
});

// ================================================================
// シナリオ7: 個店棚割の同期（ルールC）
// ================================================================

describe('シナリオ7: 標準棚割更新後の個店棚割同期', () => {
    const products: Product[] = [
        makeProduct('p1', '商品A', 100, 1, '牛肉'),
        makeProduct('p2', '商品B', 100, 2, '牛肉'),
        makeProduct('p3', '商品C', 100, 5, '豚肉'),
        makeProduct('pNew', '新商品', 100, 3, '牛肉'),
    ];

    it('標準棚割に商品追加後、同期で個店にも反映', () => {
        // 元の標準棚割: p1, p2, p3 → 更新後にpNew追加

        // 更新後の標準棚割: p1, pNew, p2, p3（pNewが追加）
        const updatedStd: StandardPlanogramProduct[] = [
            { id: 's1', productId: 'p1', shelfIndex: 0, positionX: 0, faceCount: 2 },
            { id: 's4', productId: 'pNew', shelfIndex: 0, positionX: 200, faceCount: 2 },
            { id: 's2', productId: 'p2', shelfIndex: 0, positionX: 400, faceCount: 2 },
            { id: 's3', productId: 'p3', shelfIndex: 0, positionX: 600, faceCount: 2 },
        ];

        // 同型店舗での同期 = 直接コピー
        const synced = updatedStd.map(p => ({
            id: `g-${p.id}`, productId: p.productId, shelfIndex: p.shelfIndex,
            positionX: p.positionX, faceCount: p.faceCount, isAutoGenerated: true, isCut: false,
        }));

        // 新商品が含まれている
        expect(synced.some(p => p.productId === 'pNew')).toBe(true);
        expect(synced).toHaveLength(4);
    });

    it('標準棚割から商品削除後、同期で個店からも削除', () => {
        // 元: p1, p2, p3 → 更新後: p1, p2（p3削除）
        const updatedStd: StandardPlanogramProduct[] = [
            { id: 's1', productId: 'p1', shelfIndex: 0, positionX: 0, faceCount: 2 },
            { id: 's2', productId: 'p2', shelfIndex: 0, positionX: 200, faceCount: 2 },
        ];

        const synced = updatedStd.map(p => ({
            id: `g-${p.id}`, productId: p.productId, shelfIndex: p.shelfIndex,
            positionX: p.positionX, faceCount: p.faceCount, isAutoGenerated: true, isCut: false,
        }));

        expect(synced.some(p => p.productId === 'p3')).toBe(false);
        expect(synced).toHaveLength(2);
    });

    it('小型店舗同期: 標準更新後もルールAが正しく適用', () => {
        const updatedStd: StandardPlanogramProduct[] = [
            { id: 's1', productId: 'p1', shelfIndex: 0, positionX: 0, faceCount: 3 },
            { id: 's2', productId: 'p2', shelfIndex: 0, positionX: 300, faceCount: 3 },
            { id: 's3', productId: 'p3', shelfIndex: 0, positionX: 600, faceCount: 3 },
            { id: 's4', productId: 'pNew', shelfIndex: 0, positionX: 900, faceCount: 3 },
        ];
        const storeWidth = 400; // 小型

        const result = applyRuleA(updatedStd, products, storeWidth);

        // 幅に収まっている
        const totalWidth = result.products.reduce((sum, sp) => {
            const prod = products.find(p => p.id === sp.productId)!;
            return sum + prod.width * sp.faceCount;
        }, 0);
        expect(totalWidth).toBeLessThanOrEqual(storeWidth);

        // ランク1(p1)は残っている
        expect(result.products.some(p => p.productId === 'p1')).toBe(true);
    });
});
